language: go
env:
  matrix:
  - GIMME_OS=linux GIMME_ARCH=amd64
  global:
    secure: Nn3kpBnJ3DdB513Djypls3/IM78430+oSydH2QlohUFomUt5CsLkV0xB8UwelPXRlS+DDzHTJgO9ZXWJHOoq6kffbKbAs075Yk5YP4XuOddFwPrh/FUD/QKkCIL/oxooqlwELv/n8OQV3dIRtx2qtEdK7KOX28CibZ6MZIo0ekKqtxcuJS84Aswm7D+VDcPQTup24z+Mo7vJGyqt5LcqkFS7sQOlV62rdPlShn2mKOPdQdzNwhn/PaNUqrFcazyoRqyp6qzh4aOhPiQFVjHV1AhdPaUeq0CLPHZx3Qj0r1PDVcMcTtN5sw1U5rS9XL4zjLHUtC5UK+dNOz4+2/GHewR3GAHioYQ5hCzA7Osv4jIXfYvUCxAPMeKN2WZbck+PrL9pOsi+jU8axwdozGHC4NU91jOkKpifgdY9McDdeWEoHd11s9zU+JUybuVqmftaB9+liRhF/Uq6OMvd5v+Q68rWUPfCZ2ESq6nz8HqB4PhXsNvUciYiPhV0ZUmxtrok/ge9aSh4ZOs8QeXdr89yTkeSPTyLSbRGcivP6xOnqYMYzG441nFJfMzFNUxAXdnGucibxRfplksnsDjl5Nmn3O+PDsSaa6N5UVSLuZUn74QekcoWS2ECv4mSS/wNvxGo7PPF+qh5VyzvOP5JTcO5a+FRVvvrdTlO1aDHnOeUPM0=
sudo: required
services:
- docker
go:
- 1.8.3
- tip
install:
- go get golang.org/x/tools/cmd/cover github.com/mattn/goveralls
script:
- make build
- make test
- make
- make coverage-report
matrix:
  fast_finish: true
  allow_failures:
  - go: tip
deploy:
  provider: releases
  api_key:
    secure: cDnm8TmVPHa43NrDVEjNOPYnqr/n/s/PoQ+695T9OdYnRjWDqvux1s72PS8cSSqo8U2ko2kU9ApmnlYnpIiSQE/h5hTCIZPnOdYAFWitY9ydyWhuQAixZL+X6tAr+KcdywgYF7FRSUMdXuJhxMqjTzuvdsuF8w3txhYmApG992+bD6RSwSUTh78MzGDnNmhLLhAewjuoyrj7Di3gPSDtLGdAiMbNfwzGDVuNLq5ejOM+tnjvpvWNah7jXe77W+nm/Pq8EcPBncqDae7rxJnemZKrCVZf2ZutuwfCtW34dUurYtW0gsO65wSZAReTkoIaDCrWD50ZnqWZ2cTaOhswaafBz6Cpq/NJ4JIzp2iz0/qLrOolxx01jDoTB/YjoQ4mHAtd39BfXR8la0occSDF4dqAIkMVYZV2UyX1yd5H5zdIfomHO9exuEuQwAAPzP46jCBfPFHkkXZZsna9EEIOSlQmMRHqr8Y2iM54OWh363AHh7f4YWgGRWGypRqGgAwr6+EjGqsBGZr/NrF9k/cTDrV69RQY6+tlgA18gQIyFFBCJ5FBZ7s05O89HRWlZ5mHWHfIWy/S5z0A3oMVorth2L83noS+YIVgYJjzQ9FgM9n+k7PzrSSwGSiirb+RTMBnwd8d3Ef9VeaXmfaD6nW7+f0Zrj+npdjUsu3Nn/c1VHg=
  file:
  - bundles/$TRAVIS_TAG/sloppy-darwin-amd64
  - bundles/$TRAVIS_TAG/sloppy-linux-amd64
  - bundles/$TRAVIS_TAG/sloppy-windows-amd64
  skip_cleanup: true
  on:
    repo: sloppyio/cli
    tags: true
